### ISSUE TITLE
Minor Runechat bugs

### ISSUE THREAD

**Issue by ZomgPonies** [ScorpioStation/ScorpioStation#105]
For only 1 person so far (Veloxi), it appears the black outline on runechat text isn't showing up. Please comment if this is also happening to you.

Normal Runechat:
![Capture](https://user-images.githubusercontent.com/4948622/87113926-5b5f7e80-c23d-11ea-8396-0509dc996c41.PNG)

Veloxi's Runechat:
![no-outline](https://user-images.githubusercontent.com/4948622/87113999-81851e80-c23d-11ea-9937-d3edc1f63c0f.png)

Also, sometimes there are unwanted </span> text appearing at the end of certain messages.

**Comment by blinkdog** [comment]
There was also a mention on Discord about radio messages doubling up.

**Comment by Sikroth** [comment]
Since this issue exist,

![image](https://user-images.githubusercontent.com/7857084/87203660-654bb500-c303-11ea-886f-53f533741257.png)
"</span" tag showing at the end of some messages. I think it happens for radio messages of a certain lenght. Might have to do with comms formatting? No idea

**Comment by blinkdog** [comment]
After upgrading to the latest BYOND (`513.1527`) the issue with the text not having a black outline went away.
My text is properly outlined now and much more visible.

**Comment by blinkdog** [comment]
I think I've tracked the problems with the closing `</span>` tag down.
The runechat code is written such that it believes it is operating on the raw message.

For example, if I say, `Hey there how's it going?` in the game.
The runechat code is written where it thinks it is operating on `Hey there how's it going?`
If it thinks the message is too long, it will truncate it and add `...`
So what the runechat code thinks it's doing is something like `Hey there how's it`

However `create_chat_message` is getting text that is already somewhat processed.
`Hey there how's it going?` is actually `<span blahblah><span blahblah>Hey there how's it going?</span></span>`
When that too-long truncation catches the closing span tag, it does this:
`<span blahblah><span blahblah>Hey there how's it going?</span></span`
Then it wraps the whole thing in a runechat span:
`<span runechat><span blahblah><span blahblah>Hey there how's it going?</span></span</span>`

Thus the final output ends up looking like:
`Hey there how's it going?</span`

I don't have a code fix for it yet, but I think it shouldn't be too hard if I can find an hour or two to debug it out.
