### ISSUE TITLE
Rune Chat can sometimes show </span>

### ISSUE THREAD

**Issue by Shadow-Quill** [ScorpioStation/ScorpioStation#127]
**Issue Description**:

Runechat can show </span> at the end of the runechat, if the end of the sentence gets cut off.

**What did you expect to happen**: 

HTML tags to not be shown, and instead text getting cut off normally (ie: "I cannot help but get cut o...")

**What happened instead**:

The </span> appears, if it's part of the truncated text. (ie: I cannot help but get cut o</span>...)

**Why is this bad/What are the consequences**:

Little annoying to see.

**Steps to reproduce the problem**:

Send a message of enough length (seems to be about thirty?)

**When did the problem start happening**:

Unknown.

**Extra information**:

N/A

**Comment by Shadow-Quill** [comment]
Duplicated by #105, which I didn't actually see until now.

**Comment by Samoa7** [comment]
Wasn't fixed and the 'duplicate' issue was closed, still happens a lot esp. if using a different language.

**Comment by Shadow-Quill** [comment]
> Wasn't fixed and the 'duplicate' issue was closed
No, it's still open.

**Comment by Samoa7** [comment]
Sorry, I'm blind :)
