### ISSUE TITLE
Gamemode Selection Bug

### ISSUE THREAD

**Issue by blinkdog** [ScorpioStation/ScorpioStation#139]
**Issue Description**:
Gamemode Selection did not select a valid mode

**What did you expect to happen**: 
Gamemode Selection would select a valid mode for the six players who were connected

**What happened instead**:
When the round began, the message "**Unable to choose playable game mode.** Reverting to pre-game lobby." appeared.

**Why is this bad/What are the consequences**:
Gamemode Selection is supposed to allow us to stay on Secret, but it must select a valid game mode.

**Steps to reproduce the problem**:
Start a round with six people connected.
Hope the RNG plays it out the same way.
Notice the game does not select a game mode and reverts to the lobby.

**When did the problem start happening**:
About 10 minutes ago when a new round was starting.

**Extra information**:
It may be related to enabling the configuration option `ENABLE_GAMEMODE_PLAYER_LIMIT`

**Comment by ZomgPonies** [comment]
6 players on, but were any one of those players actually readied up? If there's nobody who readies up, it resets the timer.

**Comment by ZomgPonies** [comment]
Tested and confirmed as long a as a single player is readied up, the round starts on secret(extended).
