### ISSUE TITLE
Change icon for Bluespace Floors

### ISSUE THREAD

**Issue by blinkdog** [ScorpioStation/ScorpioStation#14]
I have always hated, _hated_, **hated** the appearance of Bluespace Floor tiles in this icon:
https://github.com/ScorpioStation/ScorpioStation/blob/master/icons/turf/floors.dmi

They are usually put together to make high-speed walkways throughout the station, but I find the long chains of bright green/white static to be distracting and uncomfortable to view.

I would love it if someone could replace the current Bluespace Floor pixels with the Bluespace Floor pixels from Oracle Station:
https://github.com/OracleStation/OracleStation/blob/master/icons/turf/floors.dmi

I really liked the look of those in-game.

**Comment by trololiver112** [comment]
There is a PR up on paradise for this right now i am pretty sure
