### ISSUE TITLE
AI receives excessive PDA spam

### ISSUE THREAD

**Issue by ClockworkGolem** [ScorpioStation/ScorpioStation#146]
**Issue Description**:
When the random "PDA spam" event occurs, the AI receives an excessive number of "intercepted" spam messages -- seemingly far more than an ordinary PDA-bearing player would.

**What did you expect to happen**: 
Only as much PDA spam as an ordinary player receives, or some action that can be taken to resolve it. I've heard that other players can get a new PDA to rid themselves of spam, but the AI does not have that option.

**What happened instead**:
The AI receives a ton of spam, and it seems to scale with the number of players. There's no way to stop it short of turning off the PDA messaging server, which affects all other players. I have occasionally had to do this claiming Law 3 because it was simply too distracting.

**Why is this bad/What are the consequences**:
The AI already has to sift through a huge amount of communication and split their attention between multiple simultaneous conversations. Forcing AI players to also sort through the PDA spam makes the role even harder, but it's not an interesting challenge, merely an annoying one. This is especially bad during times of high action, when everyone wants the AI's attention and assistance. It makes it more likely that the AI player will miss real players' requests, disrupting the fiction that they are a machine intelligence capable of promptly handling multiple issues at once.

**Steps to reproduce the problem**:
1. Play as AI.
2. Wait for the "PDA spam" event to occur or trigger it manually with admin powers. It appears to be very common, perhaps 50% of rounds I've played as AI.
3. Slowly go insane.

**When did the problem start happening**:
As long as I've been playing AI on this server.

**Extra information**:
Ideally, the AI should have some action they can take (such as accessing the PDA messaging server and clicking a button to "reset encryption" or something). If this also solved the event for the other players, it would change it from pure annoyance into an opportunity for the AI (or research director) to help out the entire station.

Alternatively, I recommend removing the PDA spam event from the AI, and maybe even for all players entirely. Other than giggling about wetskrell.rx, I can't see how it's a fun event to deal with for anyone, AI or otherwise.

**Comment by garrett77** [comment]
I agree that it's an annoying event, happened on Paradise too, not sure if the same amount. PDA spam in general is pretty annoying. I feel like originally the intercepted message was so the AI could do something about it, but there is nothing they can do about it.
