### ISSUE TITLE
Painting / Canvas interactions and other bits

### ISSUE THREAD

**Issue by Sikroth** [ScorpioStation/ScorpioStation#167]
**Issue Description**:
When trying to attach a canvas to a wall painting frame, a number of odd behaviors arise.
1) If you remove a  canvas from a painting, the painting icon will not update and still display the painting
2) If you then attach a new canvas it'll pretty much stick on top of that still-stuck previous canvas instead of overriding it. More noticeable with smaller canvases
3) If you use a screwdriver on a painting frame to separate it from the wall, the currently attached canvas isn't "ejected" and is therefore lost.
4) You can't attach canvases again to a painting frame after you screwdriver it off the wall. Be it on the floor or reattached to a wall, attacking it with a canvas does nothing.

Also finished canvases take a title but they still are called "canvas". Would be nice if the title was used.
And the smaller canvases are terribly offcenter if you place them on a table.

**What did you expect to happen**: 
Canvases going in and out of painting frames correctly.

**What happened instead**:
Buggery.

**Why is this bad/What are the consequences**:
It's ugly and doesn't work as intended.

**Steps to reproduce the problem**:
- Paint canvas
- Remove previous canvas from painting frame
- attach new canvas

and

- screwdriver a painting off a wall
- fail to attach canvas afterwards

**When did the problem start happening**:
Tesmerge boys

**Extra information**:
Meme canvases because I'm dumb like that. Notice the overlapping small emoji one over the larger text one on the bottom right, and me hitting one with a canvas and it not attaching because I screwdrivered it previously.
![image](https://user-images.githubusercontent.com/7857084/89722386-4ff0a600-d9e9-11ea-8939-5a734110bedc.png)

_also technically round in progress please dont meta and come kill me_

**Comment by ZomgPonies** [comment]
This is absolutely perfect information, it's clear concise and I'll be able to address it quite rapidly. Thanks!

**Comment by ZomgPonies** [comment]
I'll add one more from my own quick test: Ghosts can't correctly examine finalized paintings

**Comment by Sikroth** [comment]
And the titles seem to have no character limit. Which if that ever gets sent to chat can be very bad or at least annoying.

Also the ' symbol breaks but when doesn't it break.

![image](https://user-images.githubusercontent.com/7857084/89722738-7ca6bc80-d9ed-11ea-9cb2-2d8f07e367ae.png)
