### ISSUE TITLE
Morgue tray erases everything.

### ISSUE THREAD

**Issue by McRamon** [ScorpioStation/ScorpioStation#196]
**Issue Description**:

Upon destruction, all the contents of morgue tray vanish from existence. And most importantly, same happens to people and NAD. 

**What did you expect to happen**: 

To all the contents to be dumped outside when it gets broken.

**What happened instead**:

I stopped to exist. NAD also stopped to exist.

**Why is this bad/What are the consequences**:

Abusable in terms of op way of assassinations and completely broken on nukie rounds, and overall just stupid.

**Steps to reproduce the problem**:

Put something inside the morgue tray. Break it. Can do it alone by laying down, opening/closing morgue tray to be put in, standing up and breaking it from inside.

**When did the problem start happening**:
 no idea

**Extra information**:

**Comment by TheMaveran** [comment]
Also an issue on paradise, minus the NAD part.

**Comment by Kiyahitayika** [comment]
PR'd on Paradise Upstream

**Comment by Kiyahitayika** [comment]
@blinkdog This can be closed. Fixed on Paradise upstream.
