### ISSUE TITLE
Using Stable Mutagen to create vox does not apply Dwarf mutation

### ISSUE THREAD

**Issue by iantine** [ScorpioStation/ScorpioStation#200]
**Issue Description**:

Using Stable Mutagen on a monkey, farwa, or other lesser mob does not create a Vox with the Dwarf mutation. If the lesser mob has a client connected when the transformation happens, the client will receive this chat message:
![zOXk6lj](https://user-images.githubusercontent.com/26665535/91456393-8c1b7600-e8c6-11ea-94ab-15ee560be02d.png)

**What did you expect to happen**: 
I expected, upon being turned into a copy of my old Vox body using a farwa/monkey/etc as a go-between, for the new vox body to have the Dwarf mutation.

**What happened instead**:
New vox body did not have the Dwarf mutation. Was regular sized, could push and pull normally.

**Why is this bad/What are the consequences**:
Vox made with stable mutagen should have the same advantages and disadvantages of other vox. If not, it should be a discussed and documented change, but I'm extremely sure this is a bug anyway.

**Steps to reproduce the problem**:
1. Take the blood of a vox and combine it with stable mutagen.
2. Inject the mixture into a farwa, monkey, wolpin or stok.
3. Observe as the resultant vox does not have dwarfism.

**When did the problem start happening**:
Noticed over this week, today being 28 Aug 2020.

**Extra information**:
I have not had this tested with human/humanised monkey to vox. It is possible that the 'small' body type of the lesser humanoid mobs is the issue.

**Comment by Kiyahitayika** [comment]
Hey @iantine! How did I not see this sooner? This should be fixed as of PR https://github.com/ScorpioStation/ScorpioStation/pull/231

The sprite resize is now located in the "on_species_gain()" proc call for Vox. This means that whenever a mob "gains" the species of Vox, they'll be resized to 0.8.

The PR also makes it so DWARF could then be applied to the already small Vox, but don't tell Admins this, alright?

**Comment by iantine** [comment]
Should be fixed as of 231
