### ISSUE TITLE
Kinetic Crusher's shoot is bugged

### ISSUE THREAD

**Issue by Sikroth** [ScorpioStation/ScorpioStation#204]
**Issue Description**:
KC doesn't shoot from your character towards where you click, instead the shoot originates from your clicked tile and always moves to the right

**What did you expect to happen**: 
Shoot coming from the gun-axe and not thin air

**What happened instead**:
Buggy projectile spawning from the clicked tile

**Why is this bad/What are the consequences**:
KC broken bad. Can't even use it to fight fauna

**Steps to reproduce the problem**:
Click while wielding a crusher, watch projectile all bugged

**When did the problem start happening**:
I am going to say while I don't mine a lot or play here a lot lately, I am positive it wasn't like this until recently. Can't say when exactly... Was that SSProjectiles thing merged? Maybe? No idea

**Extra information**:
red circle is where I clicked
![image](https://user-images.githubusercontent.com/7857084/91626601-ceb97d00-e9b0-11ea-928d-b0dde0bae24f.png)

**Comment by Kiyahitayika** [comment]
Just tested this, looks like it was fixed! Thank you for reporting and thank you to whoever fixed it!
