### ISSUE TITLE
Crew Monitors Lacking Maps

### ISSUE THREAD

**Issue by Onyxarias** [ScorpioStation/ScorpioStation#210]
**Issue Description**:
Both varieties of crew monitor, both the console and the handheld one, are missing map art for their displays.

**What did you expect to happen**: 
That a map would be shown.

**What happened instead**:
There was no map shown, instead showing a symbol in the upper left for "Missing Image"

**Why is this bad/What are the consequences**:
Not having a map removes much of the visual reference of the crew monitors, especially to players who are not familiar with the map.

**Steps to reproduce the problem**:
Open up any crew monitor interface.

**When did the problem start happening**:
Has been happening for as long as I have played Scorpio (which admittedly isn't that long :p)

**Extra information**:
I have a feeling that such a feature simply hasn't been added yet, but I figured throwing it up as an Issue might get some eyes on it!
![image_2020-08-29_195546](https://user-images.githubusercontent.com/70349271/91650210-a02fb680-ea31-11ea-8444-20e82e6749ec.png)

**Comment by Kiyahitayika** [comment]
Someone mentioned that something somewhere had to be done by someone...

**Comment by Kiyahitayika** [comment]
I think this has been fixed, except a new issue has arisen where the map shows spawn points x3
