### ISSUE TITLE
Feature Request - Vox Spawn Tank Distribution Pressure Change

### ISSUE THREAD

**Issue by Kiyahitayika** [ScorpioStation/ScorpioStation#224]
**Feature Request Description:**
Request to change the default Distribution Pressure of the "vox specialized nitrogen tank" player-controlled Vox mobs spawn with upon joining the game.

**What would you like to happen?**:
Reduce the default Distribution Pressure to **17**.

**What is currently happening?**:
The default/starting Distribution Pressure is **21**.

**Why would this feature be good/What would the consequences be?:**
This brings the default Distribution Pressure for the vox tank to be in-line with the default Distribution Pressure for the internal plasmatanks for Plasmamen player-controlled mobs upon joining the game. Reducing this pressure by default allows the tank to last significantly longer which is useful on Scorpio in particular where we have lengthy rounds due to fun! There are other means to work around this - the only reason I am submitting a PR is because Plasmamen join with a lower DP which makes their tanks last longer. Feel free to disregard if it's too much work for too little an issue.

**When did the problem start happening**:

**Extra information**:

**Comment by blinkdog** [comment]
Interesting. This isn't as straightforward as I would first expect.

The plasmaman tank appears to take the default release pressure:
[code/game/objects/items/weapons/tanks/tank_types.dm, Line 115](https://github.com/ScorpioStation/ScorpioStation/blob/1bc41ddb840b89e45cc7705b6199f978d08e57dd/code/game/objects/items/weapons/tanks/tank_types.dm#L115)
`	distribute_pressure = TANK_DEFAULT_RELEASE_PRESSURE`

But, the definition of the default is 16, which is neither 17 nor 21.

[code/__DEFINES/atmospherics.dm, Line 126](https://github.com/ScorpioStation/ScorpioStation/blob/1bc41ddb840b89e45cc7705b6199f978d08e57dd/code/__DEFINES/atmospherics.dm#L126)
`#define TANK_DEFAULT_RELEASE_PRESSURE 		16`

So something else must be involved, in either the calculation or display of the release pressure.
I think this change is worth making and was hoping to do it quickly.
Out of luck on that, but I wanted to leave these notes for myself when I round back on it.

**Comment by Kiyahitayika** [comment]
Huh. Maybe plasmaman _was_ 16... I'll look at it myself.
