### ISSUE TITLE
Feature Request - SM & Changeling Fix for Vox

### ISSUE THREAD

**Issue by Kiyahitayika** [ScorpioStation/ScorpioStation#225]
**Feature Request Description:**
Stable Mutagen + Vox Blood = Vox clone with wrong colors
Changeling Transformation + Vox = Vox with wrong colors
Changeling Transformation Sting + Vox DNA = Vox with wrong colors

**Reason:**
Vox "genetics" are not coded the same way as other species (e.g. human). Skintone is based on static UI values. Gender is not coded on the DNA level (i.e. in the DNA_UI_GENDER block). Workarounds have been found. UpdateAppearance() does not work for Vox because it would require a higher-level datum argument for these workarounds.

**Credit:**
Autumn211 (Crow/Autumn211) for getting gender from blood. Steelslayer and others for helping me learn the coding language!

**Solution:**
Replace: Line 219 *H.UpdateAppearance()* in **toxins.dm** && line 104 *H.UpdateAppearance()* in **changeling_power.dm** 
With:

```
if(istype(H.dna.species, /datum/species/vox)) //Reason: UpdateAppearance() requires different level datum. 
	switch(D.GetUIValue(13)) //Set H.s_tone based on the UI Value for Skintone
		if(632) //Vox Skintone 1, Green Vox, Hex278 = 632 Log10
			H.s_tone = 1
		if(614) //Vox Skintone 2, Dark Green Vox, Hex266 = 614 Log10
			H.s_tone = 2
		if(595) //Vox Skintone 3, Brown Vox, Hex253 = 595 Log10
			H.s_tone = 3
		if(577) //Vox Skintone 4, Grey Vox, Hex241 = 577 Log10
			H.s_tone = 4
		if(558) //Vox Skintone 5, Emerald Vox, Hex22E = 558 Log10
			H.s_tone = 5
		if(539) //Vox Skintone 6, Azure Vox, Hex21B = 539 Log10
			H.s_tone = 6
		else //Vox Skintone 0, Default Green Vox
			H.s_tone = 0

	H.change_gender(data["gender"]) //Get Vox Gender from Blood

       //Vox Body & Tail Marking - lifted from UpdateAppearance()
	var/body_marks = D.GetUIValueRange(DNA_UI_BODY_MARK_STYLE, GLOB.marking_styles_list.len)
	var/tail_marks = D.GetUIValueRange(DNA_UI_TAIL_MARK_STYLE, GLOB.marking_styles_list.len)
	H.m_colours["body"] = rgb(D.GetUIValueRange(DNA_UI_BODY_MARK_R, 255), D.GetUIValueRange(DNA_UI_BODY_MARK_G, 255), D.GetUIValueRange(DNA_UI_BODY_MARK_B, 255))
	H.m_colours["tail"] = rgb(D.GetUIValueRange(DNA_UI_TAIL_MARK_R, 255), D.GetUIValueRange(DNA_UI_TAIL_MARK_G, 255), D.GetUIValueRange(DNA_UI_TAIL_MARK_B, 255))
	if((body_marks > 0) && (body_marks <= GLOB.marking_styles_list.len))
		H.m_styles["body"] = GLOB.marking_styles_list[body_marks]
	if((tail_marks > 0) && (tail_marks <= GLOB.marking_styles_list.len))
		H.m_styles["tail"] = GLOB.marking_styles_list[tail_marks]

	H.dna.species.handle_dna(H) //<-- FOR SCORPIO ONLY - REMOVE THIS ONE LINE FOR PARADISE SERVER 
	H.regenerate_icons() //Refresh the Sprite with the new Icons
else 
	H.UpdateAppearance()
```

**Comment by blinkdog** [comment]
Ahhh interesting. Do you need any help converting this into a PR?

**Comment by Kiyahitayika** [comment]
I made it a PR on Paradise ^__^; Should I submit here as well?

**Comment by Kiyahitayika** [comment]
https://github.com/ParadiseSS13/Paradise/pull/14280

https://github.com/ParadiseSS13/Paradise/pull/14279

**Comment by Kiyahitayika** [comment]
I can definitely post here as well!

**Comment by blinkdog** [comment]
If it gets merged upstream at Paradise, we'll pick it up during an upstream merge.

I imagine there will be some feedback/changes at Paradise, so it's better to wait. If we merge it here as-is, there will be some work to de-conflict the changes between the Paradise upstream version and the version we'd merge.

If the PR gets closed upstream without being merged, then certainly open it here. At that point there is no risk of conflict, so we could merge it without worry.

**Comment by Kiyahitayika** [comment]
Yeah, let's wait to hear from Paradise. Especially since the code that ended up in the PRs there is better (and actually _works_ in regards to changeling_power.dm). :)
