### ISSUE TITLE
Invisible Mechs

### ISSUE THREAD

**Issue by EmeraldCandy** [ScorpioStation/ScorpioStation#270]
**Issue Description**:
The Seraph and Marauder mechs are visible when made and/or spawned in, however as soon as they are manned they lose all textures and become invisible. They still appear to be interactable and functional, however they cannot be seen.

**Why is this bad/What are the consequences**:
Invisible mechs bad

**Steps to reproduce the problem**:
 - Spawn Marauder/Seraph
- Enter mech

**Comment by blinkdog** [comment]
Duplicates #152 

I think @PidgeyThePirate had a fix for this; IIRC, it was setting a certain flag on the base mech while allowing customiziable mechs to override it.

Do you remember the fix, Pidgey?

**Comment by PidgeyThePirate** [comment]
Yeah, I remember. Sorry I haven't fixed it yet, I'll push a fix up today.

**Comment by blinkdog** [comment]
Thank you to @PidgeyThePirate for the quick fix on this!
