### ISSUE TITLE
ORM gives spurious error message on claiming points

### ISSUE THREAD

**Issue by blinkdog** [ScorpioStation/ScorpioStation#278]
**Issue Description**:
@EmeraldCandy reported, and I reproduced, an error where claiming points in the ORM says:

> Required access not found.

EmeraldCandy noted the points are awarded anyway, and I was able to reproduce that as well.

I think this is due to an `if` that should be an `else if` here:
https://github.com/ScorpioStation/ScorpioStation/blob/master/code/modules/mining/machine_redemption.dm#L331

```DM
	if(href_list["claim"])
		if(inserted_id)
			if(req_access_reclaim in inserted_id.access)
				inserted_id.mining_points += points
				points = 0
			if(anyuse)
				inserted_id.mining_points += points
				points = 0
			else
				to_chat(usr, "<span class='warning'>Required access not found.</span>")
```

Basically, the points are awarded in the first `if` clause, then it falls through to the second `if` clause. Since `anyuse` is false, it hits the `else` condition and falsely reports the error condition of not having the required access. Points awarded anyway, but false error message.

The fix is changing `if(anyuse)` into `else if(anyuse)`, which will allow only one of the three conditions to pass.

**What did you expect to happen**:
The ORM should award the points to those eligible without a spurious error message.

**What happened instead**:
The ORM gives you the points, but gives a spurious error message as well.

**Why is this bad/What are the consequences**:
Someone may believe the spurious error message to be genuine and waste time on it.

**Steps to reproduce the problem**:
1. Mine stuff
2. Turn it in at the ORM
3. Insert ID into the ORM
4. Claim points
5. Notice that you have claimed the points, and the error message also appears.

**Comment by Kiyahitayika** [comment]
I'm not sure an `else` will always work with an `else if`. The structure of the statements may have to be changed - still this is a very good first issue!

**Comment by blinkdog** [comment]
Looks like this was fixed upstream. The message no longer appears.
