### ISSUE TITLE
Space has no lighting

### ISSUE THREAD

**Issue by EmeraldCandy** [ScorpioStation/ScorpioStation#279]
**Issue Description**:
The tiles connected to space should have a faint glow on them to prevent the outside tiles from becomming pitch black, which they are. Something isnt configured properly to make those space tiles have light

**What did you expect to happen**:
Space should have an ambient light source

**Why is this bad/What are the consequences**:
It creates black tiles that are not fun to look at, and creates confusion on what players are actually looking at

**When did the problem start happening**:
Since the server's beginning

**Comment by Kiyahitayika** [comment]
True.
Although, I'm not sure how to address this. Absolutely open to ideas and suggestions!

**Comment by Kiyahitayika** [comment]
This looks to be a config file option.

@blinkdog  Can you look into this? I've been working on refactoring turf code and found out that there's starlight code for space turf that will only run if a certain config setting is toggled on.

**Comment by blinkdog** [comment]
> This looks to be a config file option.
> 
> @blinkdog Can you look into this? I've been working on refactoring turf code and found out that there's starlight code for space turf that will only run if a certain config setting is toggled on.

I've enabled the option in the configuration file. It should take effect next round.
