### ISSUE TITLE
Unlinked ahelp/mhelp submission

### ISSUE THREAD

**Issue by EmeraldCandy** [ScorpioStation/ScorpioStation#283]
**Issue Description**:
The ahelp/mhelp system is not properly linked to the discord when they are made

**Why is this bad/What are the consequences**:
Players may believe their ahelps are being sent to discord and other admins there when it is not. this can lead to feeling they are being ignored, and possibly not properly dealing with problematic players when they arise

**Comment by blinkdog** [comment]
Good call. I'll work on this today after work.

**Comment by blinkdog** [comment]
@EmeraldCandy I've updated the configuration on the server. It should start next round.
