### ISSUE TITLE
Add GitHub Changelog Processor

### ISSUE THREAD

**Issue by blinkdog** [ScorpioStation/ScorpioStation#29]
affected Today at 4:24 AM
@Veloxi (Katlyn Hudson) the rows are populated by tools/github_changelog_processor.php

affected Today at 4:24 AM
put that in the root of your webserver
fill the details in
and add that script in ad a github webhook

**Comment by ZomgPonies** [comment]
Poke me tomorrow and we'll go through the setup together.

**Comment by blinkdog** [comment]
I've built a changelog bot that reports changes on the ScorpioStation Discord.
