### ISSUE TITLE
[Port] Pixel Shifting for ROLEPLAY

### ISSUE THREAD

**Issue by KrulPax** [ScorpioStation/ScorpioStation#310]
LISTEN

LISTEN

I KNOW HOW IT LOOKS LIKE

BUT IT'S REALLY FUN AND CAN BE USED FOR WHOLESOME/NON HORNY REASONS
I AM NOT HORNY I SWEAR

The idea is that you can pixel shift your character to position yourself on the tile you are standing on, for, AGAIN, COMPLETELY WHOLESOME REASONS. You can lean against a wall or get closer to a table I swear It's not just horny ;u;

Seriously though it's a neat little tool that helps make movement and little quirks more transparent and I really liked it in servers like Desert Rose. Not to mention it's very non-invasive and I believe it'd be fun.

## LINK NOT SAFE FOR WORK!
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11349

**Comment by usabaker** [comment]
go to horny jail

**Comment by Kiyahitayika** [comment]
This isn't mirror. We don't use the same codebase x__x;

This also functions on clicking.

The link is also NSFW.

No.

**Comment by KrulPax** [comment]
i have no idea what mirror means but eh

**Comment by blinkdog** [comment]
I'd be in favor of porting this, so long as the changelog message in the PR is:

add: Use Ctrl-Shift-direction key to shift your characters position. Use for ~ERP~ Wholesome Roleplay.

**Comment by KrulPax** [comment]
Edited the name so that it fits better. I really don't know what the difference between port and mirror is, but I suppose in this case it's port then! Also obviously I agree with @blinkdog here.
