### ISSUE TITLE
IPC Too Fragile?

### ISSUE THREAD

**Issue by blinkdog** [ScorpioStation/ScorpioStation#43]
**Issue Description**:
IPCs seem too fragile compared to most other races.

**What did you expect to happen**: 
IPCs would have some unique weaknesses (EMP) but be at least as physically durable as the weakest organic.

**What happened instead**:
IPCs take 50% extra burn/brute damage, get decapitated more easily, and have unique weaknesses like EMP.

**Why is this bad/What are the consequences**:
* It causes me a little cognitive dissonance; mentally, I have a picture of IPCs as metallic humanoids, but in play they feel like aluminum cans or cheap plastic.
* I think IPCs have great RP flavor, but feel like this fragility might turn away players who might otherwise enjoy the race because "surprise, you're dead" isn't so much fun in practice.

**Steps to reproduce the problem**:
* Create an IPC character
* Try to survive in difficult situations

**When did the problem start happening**:
Not sure when all the decisions were put into the play balance of the IPC.

**Extra information**:
* I'd like to consider a re-balancing of the game mechanics that keep the unique flavor of IPC but lead to a more satisfying play experience.
* I don't want IPCs to be mech-light or anything that crazy durable, but maybe there is a balance point closer to organic than it currently is?

**Comment by ZomgPonies** [comment]
On the flipside, IPCs are immune to space, immune to diseases, do not breathe, are immune to limb breaks and can be easily repaired with a welder. Easy hurt, easy fix is their playstyle. If you're going to make them tougher, you need to balance their other advantages around it, otherwise they simply become the obvious choice.

More thought into their overall pros and cons is recommended, maybe start by making a clear list of each to encourage more constructive feedback.

**Comment by TheSardele** [comment]
IPCs are not immune to space, though I agree that there's more to IPCs than people give them credit for. I always saw them as a non-combat focused species in a way.

**Comment by Spacemanspark** [comment]
IPCs are better off in utility jobs. Regardless, they are hard mode.

I personally believe that @steelslayer 's PR on Paradise solves a lot of IPC problems. It could be worth looking into adding here.

**Comment by blinkdog** [comment]
@Spacemanspark was referencing this PR: https://github.com/ParadiseSS13/Paradise/pull/12628

Reading over the comments on it, it looks like a nice place to start.
Anybody opposed to merging this and giving it a test run to see how IPCs fare?

**Comment by Tokorizo** [comment]
please test it, id love to see it
