### ISSUE TITLE
The Horrible, No-Good, Very Bad Paperwork Formatting Glitch

### ISSUE THREAD

**Issue by Samoa7** [ScorpioStation/ScorpioStation#70]
**Issue Description**:

Paperwork on Paradise code is absolutely fucked up to high heaven. Simply put, most formatting tags just don't work properly and cause a line-break. I can't get a picture of what happens exactly at the moment but it looks something like this:

[b]words:[/b] apple

becomes

**words:**
apple

instead of

**words:** apple

**What did you expect to happen**: 

paperwork goodness

**What happened instead**:

paperwork badness

**Why is this bad/What are the consequences**:

The effects of this terrible awful glitch is actually pretty devastating, most of the default paperwork formats made for baycode just don't work or become eyesores. Things like bar menus just look plain ugly without formatting. This also affects the [field] tag which can actually make legitimate paperwork a bit annoying to work with, especially if inserted in the middle of a paragraph.

**Steps to reproduce the problem**:

Just use any formatting tags in a piece of paper in-game.

**When did the problem start happening**:

god only knows

**Extra information**:

**Comment by ZomgPonies** [comment]
This is the kind of fix that should also be PRed upstream, they'll appreciate it.

**Comment by ZomgPonies** [comment]
https://github.com/ParadiseSS13/Paradise/pull/12652

Possibly fixed since mid-May? Need to re-test to make sure.

**Comment by Samoa7** [comment]
yep, fixed
